name: Mauricio
description: 
meta_description: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog
domain_name: "mo-rice.github.io"
google_analytics: ""
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Mauricio"

# Disqus config
disqus-shortname: ""
